### ISSUE TITLE
Raw html table not rendering

### ISSUE THREAD

**Issue by marioa** [softwaresaved/CW-ideas#15]
Doc to markdown renders a table in HTML but this is not displaying in GitHub for:

* https://softwaresaved.github.io/CW-ideas/cw20-storyboarding-sustainability-hack/

**Comment by marioa** [comment]
To render the HTML table had to add:

```
markup:
  goldmark:
    renderer:
      unsafe: true
```

to the `config.yml` as suggested in [StackOverflow](https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted).
